services:
  db:
    image: postgres:15.5
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - ./back:/myapp
      - gem_data:/usr/local/bundle
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    stdin_open: true
    tty: true
  front:
    build: ./front
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - ./front:/myapp
    depends_on:
      - back
volumes:
  postgres_data:
  gem_data:
    driver: local
