name: Web API Deploy Pipeline
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'back/**'
      - 'front/**'
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  ECS_CLUSTER: yukutto-api-cluster
  ECS_SERVICE: yukutto-api-service
  ECS_REPOSITORY: yukutto-api-ecs
  ECS_TASK_DEFINITION_API: back/.aws/task-def-api.json

permissions:
  id-token: write
  contents: read

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          working-directory: back

      - name: Run Database Migrations for Test Environment
        env:
          RAILS_ENV: test
        run:
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run Backend Tests
        run: bundle exec rspec

      - name: Build Backend Docker Image
        run: docker build -t temp_api_image:latest -f Dockerfile.production .

      - name: Configure AWS credentials for Backend
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run:
          docker image tag temp_api_image:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker image push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

  #     - name: Register new Task Definition
  #       run: |
  #         aws ecs register-task-definition --cli-input-json file://$ECS_TASK_DEFINITION_API > task_def_output.json
  #         TASK_DEF_ARN=$(jq -r '.taskDefinition.taskDefinitionArn' task_def_output.json)
  #         echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

  #     - name: Update ECS Service with new Task Definition
  #       run: |
  #         aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition $TASK_DEF_ARN

  # build-frontend:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: front
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "21.7.1"
  #         cache: "yarn"
  #         cache-dependency-path: "package.json"

  #     - name: Install Frontend Dependencies
  #       run: yarn install

  #     - name: Run Frontend Tests
  #       run: yarn run test

  #     - name: Build Frontend
  #       run: yarn run build

  #     - name: Configure AWS Credentials for Frontend
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-region: ${{ env.AWS_REGION }}
  #         role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  #     - name: Deploy Frontend to S3
  #       run: aws s3 cp ./dist s3://yukutto-web/ --recursive
